### ISSUE TITLE
Add support for the Open Pandora (ARMv7 / OMAP3530 or DM3730) ?

### ISSUE THREAD

**Issue by sviscapi** [kallisti5/rune-image#4]
Hi,

What would be needed to add the Open Pandora (ARMv7 / OMAP3530 or DM3730, depending on the model) to your list of supported devices ?

https://pyra-handheld.com/boards/pages/pandora/

Cheers, Sam a.k.a Magic Sam from the Open Pandora community

P.S: there's a thread at the official boards: https://pyra-handheld.com/boards/threads/rune-haiku-images-on-arm.82975/

Feel free to join and say "hi" :)

**Comment by kallisti5** [comment]
I added Pandora to the u-boot builds. 
  https://github.com/haiku/firmware/tree/master/arm/pandora

Now all that's left is "everything else" :-)

**Comment by sviscapi** [comment]
Hi @kallisti5 :)

Thanks for answering so quickly !

I'm going to read this documentation about DTS, as this topic is rather new to me:

https://wiki.freebsd.org/FlattenedDeviceTree

Regarding u-boot, is your build any different from the one we currently use on the Pandora ?

https://git.openpandora.org/cgi-bin/gitweb.cgi?p=pandora-u-boot.git;a=summary

Cheers, Magic Sam

**Comment by kallisti5** [comment]
Hello! These tickets will be tracked on Haiku's bug tracker going forward.  I've gotten the tool part of the core Haiku repositories. The code lives here now:

  http://github.com/haiku/rune


The bug tracker is here:
  http://dev.haiku-os.org

Component is "Tools > Rune"



I also added a new "System > Firmware" where this request might fit in better :-)
